ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  ingressClassName: nginx
  host: vault2.k8s.djabjo.ru
  tls:
    - hosts:
        - vault2.k8s.djabjo.ru
      secretName: vault-service-tls

raft:
  replicaCount: 1
  image:
    repository: hashicorp/vault
    tag: "1.14.1"
    pullPolicy: IfNotPresent
    
  serviceAccount:
    name: vault

  affinity: {}
  nodeSelector: {}
  tolerations: []
  terminationGracePeriodSeconds: 10

  vaultEnvsConfig:
    - name: VAULT_LOG_LEVEL
      value: debug

  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1

  readinessProbe:
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1

  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

  pvc:
    size: 1Gi
    storageClassName: "local-path"
    accessMode: ReadWriteOnce

  tlsSecretName: vault-service-tls

