apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vault.fullname" . }}-config
  labels:
    {{- include "vault.labels" . | nindent 4 }}
data:
  vault.hcl: |-
    {{- .Values.vault.configHCL | nindent 4 }} 