apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-server
  namespace: {{ .Release.Namespace }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ tpl (toString $value) $ | quote }}
    {{- end }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.hosts.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vault
                port:
                  number: 8200
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
      - {{ .Values.ingress.hosts }}
      {{- range .Values.ingress.extraHosts }}
        {{- if .name }}
      - {{ tpl .name $ }}
        {{- end }}
      {{- end }}
      secretName: vault-service-tls
  {{- end }}
