apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault.fullname" . }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
  {{- with .Values.vault.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.vault.service.type }}
  ports:
    - port: {{ .Values.vault.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8201
      targetPort: cluster
      protocol: TCP
      name: cluster
  selector:
    {{- include "vault.selectorLabels" . | nindent 4 }}
  {{- if .Values.vault.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.vault.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.vault.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.vault.service.externalTrafficPolicy }}
  {{- end }} 