apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "vault.fullname" . }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
  {{- with .Values.vault.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  serviceName: {{ include "vault.fullname" . }}
  replicas: {{ .Values.vault.size }}
  selector:
    matchLabels:
      {{- include "vault.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vault.selectorLabels" . | nindent 8 }}
      {{- with .Values.vault.vaultAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "vault.serviceAccountName" . }}
      {{- with .Values.vault.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.vault.veleroEnabled }}
      # Velero backup annotations
      annotations:
        pre.hook.backup.velero.io/container: vault
        pre.hook.backup.velero.io/command: '["/bin/sh", "-c", "vault operator raft snapshot save /tmp/snapshot.snap"]'
        post.hook.backup.velero.io/container: vault
        post.hook.backup.velero.io/command: '["/bin/sh", "-c", "rm -f /tmp/snapshot.snap"]'
      {{- end }}
      containers:
        - name: vault
          image: "{{ .Values.vault.image.repository }}:{{ .Values.vault.image.tag }}"
          imagePullPolicy: {{ .Values.vault.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8200
              protocol: TCP
            - name: cluster
              containerPort: 8201
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1/sys/health
              port: http
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /v1/sys/health
              port: http
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.vault.resources.vault | nindent 12 }}
          {{- with .Values.vault.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.vault.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.vault.volumeMounts | nindent 12 }}
          {{- end }}
          {{- if .Values.vault.env }}
          env:
            {{- toYaml .Values.vault.env | nindent 12 }}
          {{- end }}
          command:
            - vault
            - server
            - -config=/vault/config/vault.hcl
          volumeMounts:
            {{- toYaml .Values.vault.volumeMounts | nindent 12 }}
            - name: vault-config
              mountPath: /vault/config
              readOnly: true
      volumes:
        {{- if .Values.vault.volumes }}
        {{- toYaml .Values.vault.volumes | nindent 8 }}
        {{- end }}
        - name: vault-config
          configMap:
            name: {{ include "vault.fullname" . }}-config
      {{- with .Values.vault.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.vault.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.vault.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.vault.storage.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: vault-raft
      spec:
        {{- if .Values.vault.storage.storageClassName }}
        storageClassName: {{ .Values.vault.storage.storageClassName }}
        {{- end }}
        accessModes:
          {{- range .Values.vault.storage.accessModes }}
          - {{ . | quote }}
          {{- end }}
        volumeMode: {{ .Values.vault.storage.volumeMode }}
        resources:
          requests:
            storage: {{ .Values.vault.storage.size }}
  {{- end }} 