  policies:
    - name: allow_secrets
      rules: |
        path "secret/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
        }

  auth:
    - type: kubernetes
      roles:
        - name: vault
          bound_service_account_names: ["vault", "vault-secrets-webhook"]
          bound_service_account_namespaces: ["vault", "vswh"]
          policies: allow_secrets
          ttl: 1h

  secrets:
    - path: secret
      type: kv
      description: General secrets.
      options:
        version: 2

  startupSecrets:
    - type: kv
      path: secret/data/accounts/aws
      data:
        data:
          AWS_ACCESS_KEY_ID: secretId
          AWS_SECRET_ACCESS_KEY: s3cr3t

    - type: kv
      path: secret/data/dockerrepo
      data:
        data:
          DOCKER_REPO_USER: dockerrepouser
          DOCKER_REPO_PASSWORD: dockerrepopassword
          
    - type: kv
      path: secret/data/mysql
      data:
        data:
          MYSQL_ROOT: pisa